- name: Add repository
  yum_repository:
    name: datadog
    description: Packages to install datadog agent packages
    baseurl: https://yum.datadoghq.com/rpm/x86_64/
    gpgcheck: true
    gpgkey: https://yum.datadoghq.com/DATADOG_RPM_KEY.public

- name: Install datadog agent
  yum: name=datadog-agent state=latest

- name: Install datadog configuration
  template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf

- name: Install check configurations
  copy: src={{ item }}.yaml dest=/etc/dd-agent/conf.d/{{ item }}.yaml
  with_items:
    - disk
    - nginx

- name: Install datadog tools like "dogwrap"
  pip: name=datadog state=latest

- name: Disable dogstatsd
  ini_file:
    dest: /etc/dd-agent/supervisor.conf
    section: "program:dogstatsd"
    option: autostart
    value: false

- name: Disable trace-agent
  ini_file:
    dest: /etc/dd-agent/supervisor.conf
    section: "program:trace-agent"
    option: autostart
    value: false

- name: Activate the datadog agent
  service: name=datadog-agent state=restarted enabled=true
