- apt_key: id=C7A7DA52 keyserver=keyserver.ubuntu.com state=present

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- apt: name=datadog-agent state=latest

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog

- copy:
    src: docker_daemon.yaml
    dest: /etc/dd-agent/conf.d/docker_daemon.yaml

- copy:
    src: nginx.yaml
    dest: /etc/dd-agent/conf.d/nginx.yaml

- copy:
    src: supervisor.conf
    dest: /etc/dd-agent/supervisor.conf

- name: Install datadog tools like "dogwrap"
  command: pip install datadog

- service: name=datadog-agent state=restarted
