- name: Install requirements
  apt: name="{{ item }}" state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install apt key for docker repo
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install docker repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main"

- name: Get output of uname -r
  command: uname -r
  register: uname_r

- name: Install recommended packages
  apt: name="{{ item }}" state=present
  with_items:
    - linux-image-extra-{{ uname_r.stdout|default('ERROR') }}
    - linux-image-extra-virtual

- name: Install docker
  apt: name=docker-engine state=present

- name: Enable docker to start on boot
  service: name=docker enabled=true state=started
