
- hosts: hosts
  vars:
    http_port: 15050
    datadog_api_key: "your api key here"

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-categories
        image: mopsalarm/pr0gramm-categories
        state: reloaded
        pull: always

        env:
          GOMAXPROCS: 8

        command: |
          --postgres 'host={{ ansible_docker0.ipv4.address }} user=postgres password=password sslmode=disable'
          --datadog {{ datadog_api_key }}

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ http_port }}:8080"
