
- hosts: hosts
  vars:
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
    - name: start new docker container for update service
      docker:
        name: pr0gramm-meta-update
        image: mopsalarm/go-pr0gramm-meta-update
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        command: >
          --postgres 'host={{ ansible_docker0.ipv4.address }} user=postgres password=password sslmode=disable'
          --datadog {{ datadog_api_key }}
