
- hosts: hosts
  vars:
    pr0gramm_meta_port: 15003
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
    - name: start new docker container for webapp
      docker:
        name: pr0gramm-meta-webapp
        image: mopsalarm/pr0gramm-meta-webapp
        state: reloaded
        pull: always

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"
          POSTGRES_HOST: "{{ ansible_docker0.ipv4.address }}"

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ pr0gramm_meta_port }}:8080"
