
- hosts: pr0-node-02, pr0-node-03
  serial: 1

  pre_tasks:
    - name: "Remove previous checkpoint file"
      file: name="/data/tags/checkpoint.store" state=absent
      when: tags_clear_checkpoint | default(false) | bool

  roles:
    - role: deploy-service
      service_name: pr0gramm-tags
      service_port: 8081
      service_docker:
        image: mopsalarm/go-pr0gramm-tags

        env:
          SERVICE_8080_NAME: pr0gramm-tags
          SERVICE_8080_CHECK_HTTP: /ping
          SERVICE_8080_CHECK_INTERVAL: 15s

        volumes:
          - "/data/tags/:/checkpoints/"

        ports:
          - "8081:8080"

        command: >
          --postgres {{ postgres_url }}
          --datadog "{{ datadog_api_key }}"
          --checkpoint-file '/checkpoints/checkpoint.store'
          --verbose
