
- hosts: hosts
  vars:
    pr0gramm_meta_port: 15003
    pr0gramm_meta_data_dir: "/data"
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

    skip_webapp: false
    skip_update_service: false

  tasks:
    - name: clone git repository
      git: repo=https://github.com/mopsalarm/pr0gramm-meta.git dest=/tmp/pr0gramm-meta update=yes

    - name: build docker image for webapp
      command: docker build -t pr0gramm/meta-webapp /tmp/pr0gramm-meta/webapp
      when: not skip_webapp

    - name: remove previous container for webapp
      docker: name=pr0gramm-meta-webapp image=pr0gramm/meta-webapp state=absent
      when: not skip_webapp

    - name: build docker image for update service
      command: docker build -t pr0gramm/meta-update /tmp/pr0gramm-meta/update
      when: not skip_update_service

    - name: remove previous container for update service
      docker: name=pr0gramm-meta-update image=pr0gramm/meta-update state=absent
      when: not skip_update_service

    - name: start new docker container for webapp
      docker:
        name: pr0gramm-meta-webapp
        image: pr0gramm/meta-webapp
        state: started

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        ports:
          - "0.0.0.0:{{ pr0gramm_meta_port }}:8080"

        volumes:
          - "{{ pr0gramm_meta_data_dir }}/:/data/:ro"

      when: not skip_webapp

    - name: start new docker container for update service
      docker:
        name: pr0gramm-meta-update
        image: pr0gramm/meta-update
        state: started

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        volumes:
          - "{{ pr0gramm_meta_data_dir }}/:/data/"

      when: not skip_update_service
