
- hosts: hosts
  vars:
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
    - name: start new docker container for update service
      docker:
        name: pr0gramm-meta-update
        image: mopsalarm/pr0gramm-meta-update
        state: restarted
        pull: always

        command: "--postgres {{ ansible_docker0.ipv4.address }}"

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"
