
- hosts: hosts
  tasks:
    - name: add hushlogin
      file: path=/root/.hushlogin state=touch

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install htop
      apt: name=htop state=present

    - name: install screen
      apt: name=screen state=present

    - name: install git
      apt: name=git state=present

    - name: install pip
      command: easy_install -U pip

    - name: install docker-py via pip
      command: pip install docker-py==1.1.0

    - name: install httpie via pip
      command: pip install httpie
