- hosts: service-postgres
  serial: 1

  vars:
    postgres_port: 5432

  pre_tasks:
    - name: Ensure data directory exists
      file: path=/data/postgres{{ postgres_version }}/ state=directory

  roles:
    - role: deploy-service
      service_name: postgres
      service_port: "{{ postgres_port }}"
      service_docker:
        image: "postgres:{{ postgres_version }}"

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "{{ postgres_port }}:5432"

        volumes:
          - "/data/postgres{{ postgres_version }}:/var/lib/postgresql/data"

- hosts: service-postgres-backup
  tasks:
    - name: Ensure backup directory
      file: name=/backup state=directory

    - name: Copy backup script
      copy: src=files/pgbackup.sh dest=/backup/pgbackup.sh mode=0755

    - name: Register cronjob for database backup
      cron:
        name: postgres-backup
        hour: 3
        minute: 0
        job: /backup/pgbackup.sh postgresql://postgres:password@{{ postgres_host }}/postgres
