
- hosts: hosts
  vars:
    feedbacky_port: 15002

    feedbacky_receiver_address: your_mail@example.com
    feedbacky_smtp_host: smtp.gmail.com
    feedbacky_smtp_user: "{{ receiver_address }}"
    feedbacky_smtp_password: your_password_here

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-feedbacky
        image: mopsalarm/pr0gramm-feedback
        state: reloaded
        pull: always

        ports:
          - "0.0.0.0:{{ feedbacky_port }}:5000"

        env:
          RECEIVER: "{{ feedbacky_receiver_address }}"
          HOST: "{{ feedbacky_smtp_host }}"
          USER: "{{ feedbacky_smtp_user }}"
          PASSWORD: "{{ feedbacky_smtp_password }}"
