
- hosts: database-hosts
  tasks:
    - name: Remove existing container
      command: docker rm -fv pr0gramm-meta-update
      ignore_errors: true
      
    - name: start new docker container for update service
      docker:
        name: pr0gramm-meta-update
        image: mopsalarm/go-pr0gramm-meta-update
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        command: >
          --postgres {{ postgres_url}}
          --datadog {{ datadog_api_key }}
