- hosts: pr0-node-02
  pre_tasks:
    - name: copy statsd config file
      copy:
        content: 'datadog: { api_key: "{{ datadog_api_key }}" }'
        dest: /data/statsd.yaml

  roles:
    - role: deploy-service
      service_name: statsd

      # service_port: 8125

      service_docker:
        image: atlassianlabs/gostatsd:7.1.0

        net: host

        command: >
          --backends datadog
          --config-path /statsd.yaml
          --flush-interval 1s
          --metrics-addr :8125
          --ignore-host

        volumes:
          - "/data/statsd.yaml:/statsd.yaml:ro"

    # - role: deploy-service
    #   service_name: statsd-proxy
    #   service_docker:
    #     image: mopsalarm/udp-proxy
    #
    #     net: host
    #
    #     command: >
    #       --source :8125
    #       --target {{ net_private_ip }}:8126
    #       --quiet
