
- hosts: pr0-node-02, pr0-node-03
  serial: 1

  roles:
    - role: deploy-service
      service_name: pr0gramm-thumby
      service_port: 15001
      service_docker:
        image: mopsalarm/pr0gramm-thumby
        ports:
          - "15001:8080"

        command: >
          --concurrent=4
