
- hosts: thumby-hosts
  vars:
    thumby_port: 15001
    datadog_api_key: "your api key here"
    docker_image: mopsalarm/pr0gramm-thumby

  tasks:
    - name: remove previous container
      docker: name=pr0gramm-thumby image={{ docker_image }} state=absent

    - name: start new docker container
      docker:
        name: pr0gramm-thumby
        image: "{{ docker_image }}"
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        command: >
          --datadog={{ datadog_api_key }}

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ thumby_port }}:8080"
          - "{{ ansible_eth0.ipv4.address }}:{{ thumby_port }}:8080"
