
- hosts: database-hosts
  roles:
    - role: deploy-service
      service_name: pr0gramm-comments
      service_port: 15041
      service_docker:
        image: mopsalarm/pr0gramm-comments:latest

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"
          POSTGRES_HOST: "{{ ansible_eth0.ipv4.address }}"

        ports:
          - "15041:8080"
