
- hosts: hosts
  vars:
    feedbacky_port: 15002

    feedbacky_receiver_address: your_mail@example.com
    feedbacky_smtp_host: smtp.gmail.com
    feedbacky_smtp_user: "{{ receiver_address }}"
    feedbacky_smtp_password: your_password_here

  tasks:
    - name: clone git repository
      git:
        repo: https://github.com/mopsalarm/feedbacky.git
        dest: /tmp/feedbacky
        update: yes

    - name: build docker image
      command: docker build -t pr0gramm/feedbacky /tmp/feedbacky

    - name: remove previous container
      docker:
        name: pr0gramm-feedbacky
        image: pr0gramm/feedbacky
        state: absent

    - name: start new docker container
      docker:
        name: pr0gramm-feedbacky
        image: pr0gramm/feedbacky
        state: started

        ports:
          - "0.0.0.0:{{ feedbacky_port }}:5000"

        env:
          RECEIVER: "{{ feedbacky_receiver_address }}"
          HOST: "{{ feedbacky_smtp_host }}"
          USER: "{{ feedbacky_smtp_user }}"
          PASSWORD: "{{ feedbacky_smtp_password }}"
