
- hosts: thumby-hosts
  tasks:
    - name: Ensure thumby container is started
      docker:
        name: pr0gramm-thumby
        image: mopsalarm/pr0gramm-thumby
        state: reloaded
        pull: always
        restart_policy: unless-stopped
        net: host

        command: >
          --datadog={{ datadog_api_key }}
          --port=15001

        ports:
          - "15001:8080"
