
- hosts: hosts
  vars:
    feedbacky_port: 15002

    feedbacky_receiver_address: your_mail@example.com
    feedbacky_smtp_host: "your smtp server"
    feedbacky_smtp_user: "your mail user"
    feedbacky_smtp_password: "your mail password"

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-feedbacky
        image: mopsalarm/pr0gramm-feedback
        state: reloaded
        pull: always

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ feedbacky_port }}:5000"

        env:
          RECEIVER: "{{ feedbacky_receiver_address }}"
          HOST: "{{ feedbacky_smtp_host }}"
          USER: "{{ feedbacky_smtp_user }}"
          PASSWORD: "{{ feedbacky_smtp_password }}"
