- hosts: hosts
  pre_tasks:
    - name: copy statsd config file
      template: src=templates/statsd.yaml dest=/data/statsd.yaml

  roles:
    - role: deploy-service
      service_name: statsd
      service_port: 8126
      service_docker:
        image: atlassianlabs/gostatsd:0.14.10

        net: host

        command: >
          --backends datadog
          --config-path /statsd.yaml
          --percent-threshold 90,95,99
          --flush-interval 60s
          --metrics-addr :8126

        volumes:
          - "/data/statsd.yaml:/statsd.yaml:ro"

    - role: deploy-service
      service_name: statsd-proxy
      service_docker:
        image: mopsalarm/udp-proxy

        net: host

        command: >
          --source :8125
          --target {{ ansible_ssh_host }}:8126
          --quiet
