
- hosts: hosts
  vars:
    http_port: 15051
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-comments
        image: mopsalarm/pr0gramm-comments:latest
        state: reloaded
        pull: always

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"
          POSTGRES_HOST: "{{ ansible_docker0.ipv4.address }}"

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ http_port }}:8080"
