- hosts: analyze-hosts
  roles:
    - role: deploy-service
      service_name: pr0gramm-analyze
      service_docker:
        image: mopsalarm/go-pr0gramm-analyze
        cpu_shares: 256

        command: >
          --cleanup --parallel 1
          --postgres {{ postgres_url }}
          --max-item-age 60
