- hosts: pr0-node-03
  roles:
    - role: deploy-service
      service_name: pr0gramm-track-settings
      service_port: 9645
      service_docker:
        image: mopsalarm/go-pr0gramm-settings

        env:
          SERVICE_8080_NAME: pr0gramm-track-settings

        volumes:
          - "/data/track-settings/:/settings/"

        ports:
          - "9645:8080"

  tasks:
    - name: Cleanup old tracking data
      cron:
        name: cleanup_tracking_data
        job: find /data/track-settings/ -ctime +30 -delete
        special_time: daily
