
- hosts: feedback-hosts
  serial: 1

  roles:
    - role: deploy-service
      service_name: pr0gramm-feedback
      service_port: 15002
      service_docker:
        image: mopsalarm/pr0gramm-feedback
        env:
          SERVICE_5000_NAME: pr0gramm-feedback

        ports:
          - "15002:5000"

        command: >
          --receiver "{{ feedback_receiver_address }}"
          --host "{{ feedback_smtp_host }}"
          --user "{{ feedback_smtp_user }}"
          --password "{{ feedback_smtp_password }}"
