- hosts: hosts

  tasks:
    - name: assures nginx config directory exists
      file: path=/data/nginx/conf.d state=directory

    - name: assures nginx data directory exists
      file: path={{ item }} state=directory
      with_items:
        - /data/nginx/data
        - /data/nginx/cache
        - /data/nginx/static

    - name: copy nginx config file
      copy:
        src: files/nginx.conf
        dest: /data/nginx/conf.d/nginx.conf

    - name: remove previous container
      docker: name=nginx image=nginx state=absent

    - name: start nginx container
      docker:
        name: nginx
        image: nginx
        state: started
        pull: always

        ports:
          - "0.0.0.0:80:80"

        volumes:
          - "/data/nginx/:/data/nginx/"
          - "/data/nginx/conf.d/:/etc/nginx/conf.d/:ro"
          - "/data/nginx/logs/:/var/log/nginx/"

- include: playbook-categories.yaml
- include: playbook-pr0gramm-meta.yaml
