
- hosts: hosts
  tasks:
    - name: copy statsd config file
      template: src=templates/statsd.yaml dest=/data/statsd.yaml

    - name: start gostatsd docker container
      docker:
        name: statsd
        image: atlassianlabs/gostatsd:0.14.10
        state: reloaded
        restart_policy: unless-stopped

        net: host

        command: >
          --backends datadog
          --config-path /statsd.yaml
          --percent-threshold 90,95,99
          --flush-interval 60s
          --metrics-addr :8126

        volumes:
          - "/data/statsd.yaml:/statsd.yaml:ro"

    - name: start statsd proxy
      tags: statsd-proxy
      docker:
        name: statsd-proxy
        image: mopsalarm/udp-proxy
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        net: host
        expose:
          - 8125/udp

        ports:
          - "8125:8125/udp"

        command: >
          --source :8125
          --target {{ ansible_eth0.ipv4.address }}:8126
          --quiet
