- hosts: categories-hosts
  serial: 1
  pre_tasks:
    - name: Create custom resolv.conf
      copy: content="nameserver {{ custom_dns_server }}" dest="/tmp/resolv.conf"

  roles:
    - role: deploy-service
      service_name: pr0gramm-categories
      service_port: 15063
      service_docker:
        image: mopsalarm/pr0gramm-categories

        ports:
          - "15063:8080"

        volumes:
          - /tmp/resolv.conf:/etc/resolv.conf:ro

        command: >
          --datadog {{ datadog_api_key }}
          --postgres {{ postgres_url }}
          --tags-service http://pr0gramm-tags.service.consul:8081
