- hosts: pr0-node-01, pr0-node-02
  serial: 1
  roles:
    - role: deploy-service
      service_name: pr0gramm-comments
      service_port: 15041
      service_docker:
        image: mopsalarm/go-pr0gramm-comments:latest

        hostname: "{{ inventory_hostname }}"

        env:
          SERVICE_NAME: "pr0gramm-comments"

        ports:
          - "15041:3000"

        command: >
          --datadog-apikey {{ datadog_api_key }}
          --postgres {{ postgres_url }}
          --verbose
