- hosts: hosts

  tasks:
    - name: assures nginx config directory exists
      file: path=/data/nginx/conf.d state=directory

    - name: assures nginx data directory exists
      file: path={{ item }} state=directory
      with_items:
        - /data/nginx/data
        - /data/nginx/cache
        - /data/nginx/static

    - name: copy nginx config file
      copy:
        src: files/nginx.conf
        dest: /data/nginx/conf.d/nginx.conf

    - name: generate (or renew ssl certificates)
      tags: cronjob
      cron:
        name: refresh_ssl_certificates
        special_time: weekly
        job: >
          sh -c '
          docker pull quay.io/letsencrypt/letsencrypt:latest ;
          docker rm -f letsencrypt ;
          docker run --rm -p 444:444 -p 81:81
          --name letsencrypt
          -v "/data/nginx/static:/webroot"
          -v "/etc/letsencrypt:/etc/letsencrypt"
          -v "/var/lib/letsencrypt:/var/lib/letsencrypt"
          quay.io/letsencrypt/letsencrypt:latest
          auth -d pr0.wibbly-wobbly.de
          --webroot --webroot-path /webroot
          -m mopsalarm.pr0gramm@gmx.de
          --renew-by-default --agree-tos ;
          killall -SIGUSR1 nginx
          '

    - name: start nginx container
      docker:
        name: nginx
        image: nginx
        state: restarted
        pull: always

        ports:
          - "0.0.0.0:80:80"
          - "0.0.0.0:443:443"

        volumes:
          - "/data/nginx/:/data/nginx/"
          - "/data/nginx/conf.d/:/etc/nginx/conf.d/:ro"
          - "/data/nginx/logs/:/var/log/nginx/"
          - "/etc/letsencrypt/:/ssl/:ro"
