
- hosts: hosts
  vars:
    pr0gramm_meta_port: 15003
    pr0gramm_meta_data_dir: "/data"
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

    skip_webapp: false
    skip_update_service: false

  tasks:
    - name: start new docker container for webapp
      docker:
        name: pr0gramm-meta-webapp
        image: mopsalarm/pr0gramm-meta-webapp
        state: reloaded
        pull: always

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        ports:
          - "0.0.0.0:{{ pr0gramm_meta_port }}:8080"

        volumes:
          - "{{ pr0gramm_meta_data_dir }}/:/data/:ro"

      when: not skip_webapp

    - name: start new docker container for update service
      docker:
        name: pr0gramm-meta-update
        image: mopsalarm/pr0gramm-meta-update
        state: reloaded
        pull: always

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        volumes:
          - "{{ pr0gramm_meta_data_dir }}/:/data/"

      when: not skip_update_service
