
- hosts: hosts
  vars:
    feedbacky_port: 5002

    receiver_address: your_mail@example.com
    smtp_host: smtp.gmail.com
    smtp_user: "{{ receiver_address }}"
    smtp_password: your_password_here

  roles:
    - common
    - feedbacky
