
- hosts: database-hosts
  roles:
    - role: deploy-service
      service_name: pr0gramm-meta-update
      service_docker:
        image: mopsalarm/go-pr0gramm-meta-update
        command: >
          --postgres {{ postgres_url }}
          --datadog {{ datadog_api_key }}
