- hosts: update-manager-hosts
  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-updates
        image: mopsalarm/pr0gramm-updates:latest
        state: reloaded
        pull: always
        restart_policy: unless-stopped
        net: host

        volumes:
          - "/data/apks:/app/apks/"

        ports:
          - "15052:8080"

        command: python -m bottle -s cherrypy -b 0.0.0.0:15052 main
