- hosts: categories-hosts
  serial: 1
  roles:
    - role: deploy-service
      service_name: pr0gramm-categories
      service_port: 15063
      service_docker:
        image: mopsalarm/pr0gramm-categories

        ports:
          - "15063:8080"

        command: >
          --datadog {{ datadog_api_key }}
          --postgres {{ postgres_url }}
          --tags-service http://139.59.157.9:8081
