
- hosts: hosts
  vars:
    http_port: 15050
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-categories
        image: mopsalarm/pr0gramm-categories
        state: reloaded

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        ports:
          - "0.0.0.0:{{ http_port }}:8080"

        volumes:
          - "/data/pr0gramm-meta.sqlite3:/data/pr0gramm-meta.sqlite3:ro"
