
- hosts: hosts
  vars:
    http_port: 15050
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"
    local_source_path: /tmp/pr0gramm-categories

  tasks:
    - name: clone git repository
      git:
        repo: https://github.com/mopsalarm/pr0gramm-categories.git
        dest: "{{ local_source_path }}"
        update: yes

    - name: build docker image
      command: docker build -t pr0gramm/categories {{ local_source_path }}

    - name: remove previous container
      docker: name=pr0gramm-categories image=pr0gramm/categories state=absent

    - name: start new docker container
      docker:
        name: pr0gramm-categories
        image: pr0gramm/categories
        state: started

        env:
          DATADOG_API_KEY: "{{ datadog_api_key }}"
          DATADOG_APP_KEY: "{{ datadog_app_key }}"

        ports:
          - "0.0.0.0:{{ http_port }}:8080"

        volumes:
          - "/data/pr0gramm-meta.sqlite3:/data/pr0gramm-meta.sqlite3:ro"
