- hosts: database-hosts
  serial: 1

  pre_tasks:
    - name: Ensure data directory exists
      file: path=/data/postgres{{ postgres_version }}/ state=directory

  roles:
    - role: deploy-service
      service_name: postgres
      service_port: 5432
      service_docker:
        image: "postgres:{{ postgres_version }}"

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "5432:5432"

        volumes:
          - "/data/postgres{{ postgres_version }}:/var/lib/postgresql/data"


    # - name: Start pgweb container
    #   tags: pgweb
    #   docker:
    #     name: postgres-web
    #     image: donnex/pgweb:latest
    #     state: reloaded
    #     pull: always
    #     restart_policy: unless-stopped
    #     publish_all_ports: true
    #
    #     command: >
    #       --host=postgres --user=postgres --pass=password
    #       --auth-user={{ pgweb_user }} --auth-pass={{ pgweb_password }} --ssl=disable
    #       --bind=0.0.0.0 --listen=8080
