
- hosts: hosts
  tasks:
    - name: copy statsd config file
      template: src=templates/statsd.yaml dest=/data/statsd.yaml

    - name: remove previous container
      command: docker rm -fv statsd
      ignore_errors: true

    - name: start new docker container
      docker:
        name: statsd
        image: atlassianlabs/gostatsd:0.13.4
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        expose:
          - 8125/udp

        command: >
          --backends datadog
          --config-path /statsd.yaml
          --percent-threshold 90,95,99
          --flush-interval 60s

        volumes:
          - "/data/statsd.yaml:/statsd.yaml:ro"

    - name: start socat proxy
      tags: statsd-proxy
      docker:
        name: statsd-proxy
        image: sequenceiq/socat:1.0.0
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        expose:
          - 8125/udp

        ports:
          - "8125:8125/udp"

        links:
          - statsd

        command: >
          socat
          UDP4-RECVFROM:8125,fork
          UDP4-SENDTO:statsd:8125
