- hosts: hosts

  vars:
    version: 9.5.3

  tasks:
    - name: assures postgres data directory exists
      file: path=/data/postgres{{ version }}/ state=directory

    - name: start postgres container
      docker:
        name: postgres  
        image: "postgres:{{ version }}"
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "{{ ansible_docker0.ipv4.address }}:5432:5432"

        volumes:
          - "/data/postgres{{ version }}:/var/lib/postgresql/data"
