- hosts: all
  roles:
    - role: swap
      tags: swap

    - role: base
      tags: base

    - role: datadog
      tags: datadog

    - role: logrotate
      tags: logrotate

    - role: journald
      tags: journald

- hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: service-discovery
      tags: service-discovery
