- hosts: hosts

  tasks:
    - name: assures postgres data directory exists
      file: path=/data/postgres/ state=directory

    - name: start postgres container
      docker:
        name: postgres
        image: postgres:9.5-beta2
        state: reloaded
        pull: always

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "{{ ansible_docker0.ipv4.address }}:5432:5432"

        volumes:
          - "/data/postgres:/var/lib/postgresql/data"
