- hosts: pr0-node-02
  pre_tasks:
    - name: copy statsd config file
      copy:
        content: 'datadog: { api_key: "{{ datadog_api_key }}" }'
        dest: /data/statsd.yaml

  roles:
    - role: deploy-service
      service_name: statsd
      service_port: 8126
      service_docker:
        image: atlassianlabs/gostatsd:2.1.0

        net: host

        command: >
          --backends datadog
          --config-path /statsd.yaml
          --percent-threshold 90,95,99
          --flush-interval 60s
          --metrics-addr :8126

        volumes:
          - "/data/statsd.yaml:/statsd.yaml:ro"

    - role: deploy-service
      service_name: statsd-proxy
      service_docker:
        image: mopsalarm/udp-proxy

        net: host

        command: >
          --source :8125
          --target {{ net_private_ip }}:8126
          --quiet
