
- hosts: hosts
  vars:
    http_port: 15052
    update_path: /data/apks

  tasks:
    - name: start new docker container
      docker:
        name: pr0gramm-updates
        image: mopsalarm/pr0gramm-updates:latest
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        volumes:
          - "{{ update_path }}/:/app/apks/"

        ports:
          - "{{ ansible_docker0.ipv4.address }}:{{ http_port }}:8080"
