- hosts: pr0-node-02
  serial: 1
  roles:
    - role: deploy-service
      service_name: pr0gramm-updates
      service_port: 15052
      service_docker:
        image: mopsalarm/pr0gramm-updates:latest

        volumes:
          - "/data/apks:/app/apks/"

        ports:
          - "15052:8080"
