- hosts: hosts

  vars:
    version: 9.5.3

  tasks:
    - name: assures postgres data directory exists
      file: path=/data/postgres{{ version }}/ state=directory

    - name: start postgres container
      docker:
        name: postgres
        image: "postgres:{{ version }}"
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "{{ ansible_docker0.ipv4.address }}:5432:5432"

        volumes:
          - "/data/postgres{{ version }}:/var/lib/postgresql/data"


    - name: start pgweb container
      tags: pgweb
      docker:
        name: postgres-web
        image: donnex/pgweb:latest
        state: reloaded
        pull: always
        restart_policy: unless-stopped

        command: >
          --host=postgres --user=postgres --pass=password
          --auth-user={{ pgweb_user }} --auth-pass={{ pgweb_password }} --ssl=disable
          --bind=0.0.0.0 --listen=8080

        links:
          - postgres

        ports:
          - "8080:8080"
