- hosts: database-hosts
  serial: 1

  vars:
    postgres_port: 5432

  pre_tasks:
    - name: Ensure data directory exists
      file: path=/data/postgres{{ postgres_version }}/ state=directory

  roles:
    - role: deploy-service
      service_name: postgres
      service_port: "{{ postgres_port }}"
      service_docker:
        image: "postgres:{{ postgres_version }}"

        env:
          PGDATA: /var/lib/postgresql/data/pg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        ports:
          - "{{ postgres_port }}:5432"

        volumes:
          - "/data/postgres{{ postgres_version }}:/var/lib/postgresql/data"

- hosts: database-backup-hosts
  tasks:
    - name: Register cronjob for database backup
      cron:
        name: postgres-backup
        hour: 4
        minute: 0
        job: docker run --rm -v /backup:/backup postgres:9.6-alpine pg_dump -Fc -f /backup/pr0gramm.dump --dbname postgresql://postgres:password@{{ postgres_host }}/postgres
