
- hosts: webm-hosts
  vars:
    gif2webm_port: 15000
    datadog_api_key: "your api key here"
    datadog_app_key: "your app key here"

  tasks:
  - name: start new docker container
    docker:
      name: pr0gramm-gif2webm
      image: mopsalarm/gif2webm
      state: reloaded
      pull: always

      env:
        DATADOG_API_KEY: "{{ datadog_api_key }}"
        DATADOG_APP_KEY: "{{ datadog_app_key }}"

      ports:
        - "{{ gif2webm_port }}:5000"

      volumes:
        - "/data/webm:/app/webm"

  - name: generate cronjob to restart the webm container
    tags: cronjob
    cron:
      name: restart webm container
      special_time: daily
      job: >
        sh -c "rm -f /data/webm/* ; docker restart pr0gramm-gif2webm"
