
- name: clone git repository
  git: repo=https://github.com/mopsalarm/thumby.git dest=/tmp/thumby update=yes

- name: build docker image
  command: docker build -t thumby /tmp/thumby

- name: remove previous container
  docker: name=thumby image=thumby state=absent

- name: start new docker container
  docker:
    name: thumby
    image: thumby
    state: started

    ports:
      - "0.0.0.0:{{ thumby_port }}:5000"

    volumes:
      - "/data/thumby:/usr/src/app/images"
