- name: create config directory
  file: name="/data" state="directory"

- name: copy logrotate config file
  copy: src=logrotate.conf dest="/data/logrotate.conf"

- name: start new docker container
  docker:
    name: logrotate
    image: eranchetz/logrotate
    state: reloaded
    restart_policy: unless-stopped

    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:rw"
      - "/data/nginx/logs:/data/nginx/logs:rw"
      - "/data/logrotate.conf:/etc/logrotate.conf:ro"
