- name: Install logrotate
  package: name=logrotate state=present

- name: Copy logrotate config files
  copy: src={{ item }}.conf dest="/etc/logrotate.d/{{ item }}"
  with_items:
    - nginx
    - syslog
