- name: Remove containers
  command: docker rm -fv registrator consul
  ignore_errors: true

- name: Start consul container
  docker:
    name: consul
    image: consul:0.7.2
    state: reloaded
    restart_policy: unless-stopped
    net: host
    env:
      CONSUL_LOCAL_CONFIG: "{{ consul_config|to_json }}"
    command: >
      agent -ui -server
        --bind=0.0.0.0
        --client=0.0.0.0
        --advertise={{ consul_advertise_address }}
        --encrypt={{ consul_secret }}
        --node={{ inventory_hostname }}
        {% if consul_bootstrap %}
          -bootstrap-expect=1
        {% endif %}
        {% for host in consul_hosts %}
          {% if host != consul_advertise_address %}
            -retry-join={{ host }}
          {% endif %}
        {% endfor %}

- name: Remove registrator container
  tags: registrator
  command: docker rm -fv registrator
  ignore_errors: true

- name: Start the registrator container
  tags: registrator
  docker:
    name: registrator
    image: gliderlabs/registrator:v7
    state: reloaded
    restart_policy: unless-stopped
    net: host
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: >
      --cleanup --ip={{ ansible_ssh_host }} consul://{{ consul_advertise_address }}:8500
