docker_install: false

postgres_version: 10.4-alpine

postgres_host: "{{ hostvars[groups['service-postgres'][0]].net_private_ip }}"
postgres_url: "postgres://postgres:password@{{ postgres_host }}?sslmode=disable"

consul_hosts: "{{ groups['service-consul']|map('extract', hostvars, 'net_private_ip')|list }}"

dnsmasq_extra_args: -S /consul/{{ net_private_ip }}#8600

dns_server: "{{ hostvars[groups['service-dnsmasq'][0]].net_private_ip }}"

consul_advertise_address: "{{ net_private_ip }}"
