postgres_version: 9.5.3

postgres_url: "postgres://postgres:password@46.101.134.19?sslmode=disable"

consul_hosts:
  - 46.101.134.19
  - 139.59.157.9

firewall_allow_hosts:
  - 46.101.134.19
  - 139.59.157.9
