
- name: clone git repository
  git: repo=https://github.com/mopsalarm/pr0gramm-meta.git dest=/tmp/pr0gramm-meta update=yes

- name: build docker image
  command: docker build -t pr0gramm/meta /tmp/pr0gramm-meta/webapp

- name: remove previous container
  docker: name=pr0gramm-meta image=pr0gramm/meta state=absent

- name: start new docker container
  docker:
    name: pr0gramm-meta
    image: pr0gramm/meta
    state: started

    ports:
      - "0.0.0.0:{{ pr0gramm_meta_port }}:8080"

    volumes:
      - "/data/pr0gramm-meta.sqlite3:/usr/src/app/pr0gramm-meta.sqlite3:ro"
