- name: Add hushlogin
  file: path=/root/.hushlogin state=touch

- name: Install epel release repository
  package: name=epel-release state=present

- name: Install packages
  package: name={{ item }} state=present
  with_items:
    - htop
    - screen
    - git
    - python2-pip
    - NetworkManager-glib

- name: Install docker-py via pip
  pip: name=docker-py version=1.9.0

- name: Install httpie via pip
  pip: name=httpie state=latest

- name: Install ffind via pip
  pip: name=ffind state=latest

- name: Disable firewalld
  notify: restart docker
  service: name=firewalld state=stopped enabled=false

- name: Configure docker
  notify: restart docker
  copy: src=docker-config.json dest=/etc/docker/daemon.json

- name: Enable network manager
  service: name=NetworkManager state=started enabled=true

- name: Configure internal network
  tags: private-network
  nmcli:
    conn_name: private-net
    type: ethernet
    ifname: eth1
    ip4: "{{ net_private_ip }}/24"
    state: present
    mtu: 1450

- name: (re-)activate network
  command: nmcli c up private-net
